# HW#2, Otimization:  

Problem 1a):  

For **u**=[2, -1, 4]$^{T}$ find following value. ||**u**||$_2$***u**

In [ ]:
import numpy as np

u=[2, -1, 4]

print('Vector u=' + str(u))

umag = np.linalg.norm(u,2)

print('Magnitude of u= ' + str(umag))

print('u*umag= ', [x * umag for x in u])

print('u*umag= ', umag * np.array(u))

Problem 1b):  

For **A**=([2, 1, -1]; [1, 4, 3]; [-1, 3, 4]) and **u**=[2, -1, 4]$^{T}$ find **A*u**:

In [ ]:
import numpy as np

A=np.array([[2, 1, -1], [1, 4, 3], [-1, 3, 4]])

print('A=', A,'\n')

u=np.array([2, -1, 4])

print('u= ', u, '\n')

p=A.dot(u)

print('p= ', p)

Problem 1c):  

For **B**=([1, -1, 0, 3]; [-1, 2, 4, 2]; [0, -1, 4, -2]; [2, 3, 1, 1]) and **u**=[2, -1, 4]$^{T}$ find **B*u**:

**B** is a 4x4 matrix and **u** is a 3x1 matrix. Since inner dimensions do not agree the desired operation cannot be carried out.

In [ ]:
import numpy as np

B=np.array([[1, -1, 0, 3], [-1, 2, 4, 2], [0, -1, 4, -2],[2, 3, 1, 1]])

print('B=', B,'\n')

u=np.array([2, -1, 4])

print('u= ', u, '\n')

p=B.dot(u)

print('p= ', p)

Problem 1d):  

For **v**=[-2, 0, 1, 1] and **u**=[2, -1, 4]$^{T}$ find **v*u**:

If **u** was not transposed then its size would be 3x1, conversly **v** dimension is 1x4. Since inner dimensions do not agree the desired operation cannot be carried out (i.e. **v**=1x4 and **u**=3x1, hence 4 $\ne$ 3)

In [ ]:
import numpy as np

v=np.array([-2, 0, 1, 1])

print('v=', v,'\n')

u=np.array([2, -1, 4])

print('u= ', u, '\n')

p=v.dot(u)

print('p= ', p)

Problem 1e):  

Find (**v** $*$ **w**) $*$ **v**

In [6]:
import numpy as np

v=np.array([-2, 0, 1, 1])

w=np.array([4, 1, -1, 3])

print('Vector v=', v, '\n')
print('Vector w=', w, '\n')

p = v.dot(w)*v
print('After (v*w)*v vector p=', p, '\n')



Vector v= [-2  0  1  1] 

Vector w= [ 4  1 -1  3] 

After (v*w)*v vector p= [12  0 -6 -6] 



Problem 1f):

Find **A**$^{2}$

In [2]:
import numpy as np

A=np.matrix([[2, 1, -1], [1, 4, 3], [-1, 3, 4]])

print('A=', A,'\n')

B=A**2

#another way to square a matrix
C=np.linalg.matrix_power(A, 2)

print('B=', B,'\n')

print('C=', C)

A= [[ 2  1 -1]
 [ 1  4  3]
 [-1  3  4]] 

B= [[ 6  3 -3]
 [ 3 26 23]
 [-3 23 26]] 

C= [[ 6  3 -3]
 [ 3 26 23]
 [-3 23 26]]


Problem 1g):  

Find $sin(u + v)$

In [8]:
import numpy as np

u=np.matrix([2, -1, 4])
v=np.matrix([-2, 0, 1, 1])

d=u+v

print('d= ', d, '\n')

#would work if u and v matched dimensions
e=np.sin(d)

print('e= ', e, '\n')

ValueError: operands could not be broadcast together with shapes (1,3) (1,4) 

Problem 1g:  

Find $||u||_2 + ||w||_2$

In [11]:
import numpy as np

u=np.matrix([2, -1, 4])
w=np.matrix([4, 1, -1, 3])

unorm2=np.linalg.norm(u,2)
wnorm2=np.linalg.norm(w,2)

t=unorm2+wnorm2

print('t= ', round(t, 2))

t=  9.78


Problem 2:

Find $||*||_1, ||*||_2, ||*||_{inf}$ for $u$

In [20]:
import numpy as np

u=np.matrix([2, -1, 4])

unorm1=np.linalg.norm(u, np.inf)
unorm2=np.linalg.norm(u, 2)
unorm_inf=np.linalg.norm(u, 1)

print('||u||_1= ', unorm1, '\n')
print('||u||_2= ', unorm2, '\n')
print('||u||_inf= ', unorm_inf)

||u||_1=  7 

||u||_2=  4.58257569496 

||u||_inf=  4


Problem 3:  
    
Find $\bigtriangledown$ and $\bigtriangledown^2$ for the following functions:

$f(\vec{x}) = 2x_1^{2} + 3x_2^{3} - 2x_3$  
$g(\vec{x}) = \sin{(2x_1)} + e^{-x_2} + x_3{3}$  


In [34]:
# sympy used for symbolic math calculations. Do not invoke numpy while doing
# symbolic math as it may give unexpected errors.
from sympy import *
#from numpy import *

x1, x2, x3, f, g = symbols("x1 x2 x3 f g", real = True)
                           
f = 2*x1**2 + 3*x2**3 - 2*x3
                           
f1 = diff(f,x1)
print(f1, '\n')

f2=diff(f,x2)
print(f2, '\n')

f3=diff(f,x3)
print(f3, '\n')

g=sin(2*x1)+exp(-x2)+x3**3

g1 = diff(g,x1)
print(g1, '\n')

g2=diff(g,x2)
print(g2, '\n')

g3=diff(g,x3)
print(g3, '\n')

f12 = diff(f,x1,2)
print(f12, '\n')

f22=diff(f,x2,2)
print(f22, '\n')

f32=diff(f,x3,2)
print(f32, '\n')

g12 = diff(g,x1,2)
print(g12, '\n')

g22=diff(g,x2,2)
print(g22, '\n')

g32=diff(g,x3,2)
print(g32, '\n')

4*x1 

9*x2**2 

-2 

2*cos(2*x1) 

-exp(-x2) 

3*x3**2 

4 

18*x2 

0 

-4*sin(2*x1) 

exp(-x2) 

6*x3 



<div>
<span style="vertical-align: middle;">A</span>
<table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" width="100" align="left">
<tr>
    <td height="10" width="10%" style = "text-align: right;">2 &nbsp;</td>
    <td height="10" width="20%" style = "text-align: right;">1 &nbsp;</td>
    <td height="10" width="20%" style = "text-align: right;">-1 &nbsp;</td>
</tr>
<tr>
    <td height="10" width="20%" style = "text-align: right;">1 &nbsp;</td>
    <td height="10" width="20%" style = "text-align: right;">4 &nbsp;</td>
    <td height="10" width="20%" style = "text-align: right;">3 &nbsp;</td>
</tr>
<tr>
    <td height="10" width="20%" style = "text-align: right;">-1 &nbsp;</td>
    <td height="10" width="20%" style = "text-align: right;">3 &nbsp;</td>
    <td height="10" width="20%" style = "text-align: right;">4 &nbsp;</td>
</tr>
</table>
</div>